### PR TITLE
#362 chore: upgrade Keycloak to 16.1.0

### PR DESCRIPTION
**Pull request by zsinnema**
I've tested the new CH version with MNP and everything seems to work as it should.

### CODE REVIEW

**Comment by filippomc** [comment]
The upgrade didn't work for me on a hot replacement (see error below), while it worked after deleting the previous deployment.
This is an issue for the business continuity and may create a lot of waste time to the unaware developer. 
We should think about a way to properly track update issues and in general major version updates in the release notes.
Also the issue #362 does not really explain the reason of this major update.

I want to take this kind of potential upgrade issues seriously, because if we start having uncontrolled issues the response will be not to upgrade the cloudharness version at all.

```
10:12:18,245 ERROR [org.infinispan.CLUSTER] (thread-6,ejb,accounts-78dc8c5fdd-m2bfs) ISPN000474: Error processing request 1@accounts-bcd77d457-ph7h6: org.infinispan.commons.CacheException: Unknown command id 90!
at org.infinispan@10.1.8.Final//org.infinispan.commands.RemoteCommandsFactory.fromStream(RemoteCommandsFactory.java:214)
at org.infinispan@10.1.8.Final//org.infinispan.marshall.exts.ReplicableCommandExternalizer.readCommandHeader(ReplicableCommandExternalizer.java:99)
...
```

**Comment by zsinnema** [comment]
I ran the upgrade on IFN staging and no error was shown and keycloak was updated to v16

here you can find the issue that this pr is solving: https://www.keycloak.org/2021/12/cve

**Comment by filippomc** [comment]
> I ran the upgrade on IFN staging and no error was shown and keycloak was updated to v16
> 
> here you can find the issue that this pr is solving: https://www.keycloak.org/2021/12/cve

Thanks for the specification. What are your thoughts about tracking potential issues like this? I'm thinking about adding a tag to the issues so it's easier to track them in the release notes

**Comment by zsinnema** [comment]
@filippomc do you mean how to generate release notes? In GitHub it's possible to create a release and there you can generate the release notes by getting all commit messages (same you can do with plain git). What do you think of adding the url to the git commit message?

**Comment by filippomc** [comment]
@zsinnema I've added some tags to github about the scope and general warnings. I think we need something more high level in the release notes than commit messages to make it clear at a glance if there is something to worry about when upgrading the ch version.

**Comment by filippomc** [comment]
#361 also upgrade keycloak. Should we closing.

**Pull request closed without merging**
